labels: [enhancement, feature-request]

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thanks for taking the time to suggest a new feature! Please fill out the information below to help us understand your idea.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: "I would like to..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve or the use case it would enable.
      placeholder: "As a developer building a scheduling app, I need to..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working? Include API examples if applicable.
      placeholder: |
        ```tsx
        <TimelineRow
          newProp="value"
          onNewEvent={(data) => console.log(data)}
        >
          ...
        </TimelineRow>
        ```
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've tried using... but it doesn't work well because..."
    validations:
      required: false

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: How would this feature benefit the library?
      options:
        - label: Solves a common use case
        - label: Improves developer experience
        - label: Enhances performance
        - label: Increases accessibility
        - label: Better TypeScript support

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: "Links to similar features in other libraries, mockups, etc."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing this feature?
      options:
        - label: I'd like to work on this feature myself
        - label: I can help test this feature
        - label: I can provide design/UX feedback
